FROM node:18-alpine AS base
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER nextjs

COPY --from=installer --chown=nextjs:nodejs package.json /app/apps/web/package.json
COPY --from=installer --chown=nextjs:nodejs next.config.mjs /app/apps/web/next.config.mjs
COPY --from=installer --chown=nextjs:nodejs .next /app/apps/web/.next
COPY --from=installer --chown=nextjs:nodejs node_modules /app/apps/web/node_modules
COPY --from=installer --chown=nextjs:nodejs ../../node_modules /app/node_modules

WORKDIR /app/apps/web
EXPOSE 3000

CMD ["npm", "start"]