version: '3.9'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: on-failure
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_TCP_PORT: $MYSQL_PORT
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: