version: '3.9'
services:
  mysql_db:
    image: mysql:8.0.25
    container_name: mysql_8_0_25
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db-backup:/var/lib/mysql

volumes:
  db-backup: